### ISSUE TITLE
@each: Variables didn't get resolved for @include mixins

### ISSUE THREAD

**Issue by paulAtSlim** [jonathantneal/postcss-advanced-variables#112]
I have the following scss snippet which i used in an old project. 

```scss
@each $v in (small, medium, large, xl, xxl) {
	@include $(v) {
		@for $i from 1 to 12 {
			&-$(v)-$(i) {
				grid-template-columns: repeat($(i), 1fr);
			}
		}
	}
}
``` 

When I run it I get the error
`[vite:css] [postcss] postcss-sassy-mixins: /var/www/html/packages/acv_core/src/scss/components/forms.scss:65:5: Undefined mixin $`

The only way I could make it run again is to use `postcss-each` in the version `0.10.0` which is no longer maintained (in the version 1.10.0 it throws the same error)

is it just currently not supporten in the @each helper of advanced-variables or did I have to change my syntax?
I also tryed `#{$v}`but no luck.
