### ISSUE TITLE
Variable referencing variables not handled ?

### ISSUE THREAD

**Issue by onigoetz** [jonathantneal/postcss-advanced-variables#23]
Hi,

I was wondering, I have a project with lots of variables, and it seems that variable variables aren't supported ?

An example like this :

``` scss
$var1: blue;
$var2: $var1;

body {
 color: $var2;
}
```

If it actually isn't supported yet, is it planned for the future ?
