### ISSUE TITLE
Replace eachAtEachRule with postcss-each please

### ISSUE THREAD

**Issue by corysimmons** [jonathantneal/postcss-advanced-variables#30]
eachAtEachRule doesn't accept an iterator whereas postcss-each does.

If this isn't possible for some reason, let me know and I'll PR an iterator.

``` scss
// works in postcss-each
@each $val, $i in foo, bar {
  .icon-$(val) {
    background: url("$(val)_$(i).png");
  }
}
```
