### ISSUE TITLE
Your current PostCSS version is 6.0.6, but postcss-advanced-variables uses 5.2.17

### ISSUE THREAD

**Issue by mov1er** [jonathantneal/postcss-advanced-variables#36]
I'm use gulp run postcss task.I got this issue when I run the task.
All devDependencies's version are latest.What's wrong on earth?

**Comment by zyy7259** [comment]
When use the `@each` syntax with postcss 6, it will throw an error

```css
@each $icon in (foo, bar, baz) {
	.icon-$icon {
		background: url('$dir/$icon.png');
	}
}
```

Please update to postcss 6~
