### ISSUE TITLE
Font name variables supposed to work?

### ISSUE THREAD

**Issue by arxpoetica** [jonathantneal/postcss-advanced-variables#40]
It broke somewhere after version `1.2.2`...? Not sure if it was in `2.0.0.` or `2.1.0`. The following use to translate:

```scss
$poppins: 'Poppins', 'Helvetica Neue', Helvetica, Arial, sans-serif;
body {
    font-family: $poppins;
}

[to]

body {
    font-family: 'Poppins', 'Helvetica Neue', Helvetica, Arial, sans-serif;
}
```

but now it's outputting like so:

```scss
body {
    font-family: ('Poppins','Helvetica Neue',Helvetica,Arial,sans-serif);
}
```

Any ideas? Might need to roll back until fixed.
