### ISSUE TITLE
Cannot set parameter default to other variable in mixin

### ISSUE THREAD

**Issue by lohfu** [jonathantneal/postcss-advanced-variables#54]
I would like to set default values of mixin parameters to the value of another variable, but postcss will output the variable name instead.

Ie the following code:

```scss
@mixin .container($max-width: $content-max-width, $gutter: global-gutter) {
  width: calc(100% - $gutter);
  max-width: $max-width;
  margin: 0 auto;
}

#app > .container {
  @include .container;
}
```

will output

```css
#app > .container {
  width: calc(100% - $global-gutter);
  max-width: $content-max-width;
  margin: 0 auto;
}
```

Are there any plans to support similar syntax?
