### ISSUE TITLE
String variable replacement includes quotes

### ISSUE THREAD

**Issue by ivantm** [jonathantneal/postcss-advanced-variables#57]
postcss-advanced-variables does not trim quotes (single or double) around variable values and it doesn't seem like there is any option to change this. This prevents empty strings from working (e.g. if I have a mixin where the default value of an argument is an empty string).

Input:

```scss
$suffix: ""

.invalid#{$suffix} {
    color: red;
}
```

Output:

```css
.invalid"" {
    color: red;
}
```

Expected output (this is what sass would produce):

```css
.invalid {
    color: red;
}
```

You can reproduce this in the [scss test case](https://github.com/jonathantneal/postcss-advanced-variables/blob/master/test/scss.scss) simply by wrapping `green` in line 1 with single or double quotes. The expected output should be the same, but the test fails.
