### ISSUE TITLE
Variables strings

### ISSUE THREAD

**Issue by Trolleymusic** [jonathantneal/postcss-advanced-variables#62]
I'm having some trouble with outputting variable as encapsulated strings - it may just be confusion on my part, but let me give you some examples:

If I add a string as a variable, eg:

```postcss
$font-custom-name: "Custom Font";
```

In Sass I would use:

```sass
font-family: "#{$font-custom-name}"
```

And end up with this:

```css
font-family: "Custom Font";
```

Every way I try to output it ...

```postcss
.example-1 {
  font-family: $font-custom-name;
}

.example-2 {
  font-family: "$font-custom-name";
}

.example-3 {
  font-family: $(font-custom-name);
}

.example-4 {
  font-family: "$(font-custom-name)";
}

.example-5 {
  font-family: $font-custom-name;
}

.example-6 {
  font-family: "#{$font-custom-name}";
}

.example-7 {
  font-family: ""$font-custom-name"";
}

.example-8 {
  font-family: '$font-custom-name';
}
```

... none of them seem to come out how I want them to.

```css
.example-1 {
  font-family: Custom Font;
}

.example-2 {
  font-family: ,Custom Font;
}

.example-3 {
  font-family: Custom Font;
}

.example-4 {
  font-family: ,Custom Font;
}

.example-5 {
  font-family: Custom Font;
}

.example-6 {
  font-family: ,Custom Font;
}

.example-7 {
  font-family: ,Custom Font;
}

.example-8 {
  font-family: '"Custom Font"';
}
```
