### ISSUE TITLE
Can't use variables for custom property names in @each loops

### ISSUE THREAD

**Issue by spaceninja** [jonathantneal/postcss-advanced-variables#75]
I'm trying to set up an each loop to render a list of layers as custom properties that we'll use for z-index values in our pattern library. However, I can't find a way to get the layer variable to render as a custom property name.

Here's a test case:

```css
$layers: alpha, beta, gamma, delta;

:root {
  @each $layer $i in $layers {
    --#{$layer}: $i;
  }
}

.beta {
  z-index: var(--beta);
}
```
